# Generated by Django 5.1.2 on 2024-10-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='velnoteuser',
            name='role',
            field=models.CharField(default='receiver', max_length=10),
        ),
    ]
